# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a44978afffbc851dd9bcf7bade2c809ea452fa3748314d921c9a345df0c17bcf4d65a3cda3c73bc2f1be11c070f57bc73761d240aff548766190310ca1257f2

test:
  secret_key_base: af874b1f2764cc23ac303252a3e6ed13af610b1089776d18f465df6b129aee3bb2a8c05beb8af9299cae939f6b700089b830946a13676c3cd638d83cf86a9f2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
